name: "Test"

on:
  workflow_dispatch: 
  push:
    branches:
      - main
jobs:
  composite_test:
    name: Repo composite
    uses: alexwolfg/github_actions_lesson1/.github/workflows/Lesson3_exer1.yml@main
    with:
      ACTOR: ${{ github.actor }}
    
